// export const metadata = {
//   title: "PestPaw app",
//   description: "Generated by create next app",
// };
"use client";

import { usePathname } from "next/navigation";

import AdditionalNav from "@/components/AdditionalNav/AdditionalNav";
import BackBtn from "@/components/BackBtn/BackBtn";
import SearchForm from "@/components/SearchForm/SearchForm";

export default function PagesLayout({ children }) {
  const pathname = usePathname();

  return (
    <section>
      <SearchForm />
      <AdditionalNav />
      <BackBtn />
      <h2>{pathname.replace("/", "").toUpperCase()}</h2>
      {children}
    </section>
  );
}
