// export const metadata = {
//   title: "PestPaw app",
//   description: "Generated by create next app",
// };

import AdditionalNav from "@/components/AdditionalNav/AdditionalNav";
import Search from "@/components/Search/Search";

export default function PagesLayout({ children }) {
  return (
    <section>
      <Search />
      <AdditionalNav />
      {children}
    </section>
  );
}
