import Header from "@/components/Header/Header";
import "./globals.css";
import { Jost } from "next/font/google";
import Navbar from "@/components/Navbar/Navbar";

const jost = Jost({ subsets: ["latin"] });

export const metadata = {
  title: "PestPaw app",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={jost.className}>
        <div>
          <Header />
          <Navbar />
        </div>
        <main className="mainBg">{children}</main>
      </body>
    </html>
  );
}
