import { Jost } from "next/font/google";
import SearchProvider from "@/contexts/searchContext";

import Navbar from "@/components/Navbar/Navbar";
import Header from "@/components/Header/Header";
import "./globals.css";

const jost = Jost({ subsets: ["latin"] });

export const metadata = {
  title: "PestPaw app",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <SearchProvider>
        <body className={jost.className}>
          <header>
            <Header />
            <Navbar />
          </header>
          <main className="mainBg">{children}</main>
        </body>
      </SearchProvider>
    </html>
  );
}
